name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
    mongo-uri: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    mongo-username: ${{vars.mongo_username}}
    mongo-password: ${{secrets.mongo_password}}     
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          fail-fast: false
          matrix:
            nodejs_version: [24,23,22]
            os: [ubuntu-latest,windows-latest,macos-latest]
            exclude: 
                - nodeJs_version: 22
        runs-on: ${{matrix.os}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4.2.2

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4.4.0
          with:
            node-version: ${{matrix.nodejs_version}}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4.6.2
          with:
            name: Mocha-Test-Result
            path: test-results.xml
           